---
title: dstull.github.io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: "/:categories/:year/:month/:day/:title"
exclude:
- ".rvmrc"
- ".rbenv-version"
- README.md
- Rakefile
- changelog.md
highlighter: pygments
tagline: Site Tagline
author:
  name: doug stull
  email: hammer098@yahoo.com
  github: dstull
  twitter: dougstull
  feedburner: feedname
production_url: http://dstull.github.io
JB:
  version: 0.3.0
  BASE_PATH: false
  ASSET_PATH: false
  archive_path: "/archive.html"
  categories_path: "/categories.html"
  tags_path: "/tags.html"
  atom_path: "/atom.xml"
  rss_path: "/rss.xml"
  markdown: redcarpet
  redcarpet:
    extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - with_toc_data
  comments:
    provider: disqus
    disqus:
      short_name: jekyllbootstrap
    livefyre:
      site_id: 123
    intensedebate:
      account: 123abc
    facebook:
      appid: 123
      num_posts: 5
      width: 580
      colorscheme: light
  analytics:
    provider: google
    google:
      tracking_id: UA-123-12
    getclicky:
      site_id: 
    mixpanel:
      token: _MIXPANEL_TOKEN_
    piwik:
      baseURL: myserver.tld/piwik
      idsite: '1'
  sharing:
    provider: false
